FROM python:3.9.9-slim-buster

RUN apt-get update && apt-get install -y  --no-install-recommends \
	ffmpeg \
	libsm6 \
	libxext6 \
	python3-tk \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip

COPY ./requirements.txt requirements.txt

RUN pip install -r requirements.txt

WORKDIR /imgs

CMD /bin/bash